var ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  UNSUPPORTED_VERSION: "UNSUPPORTED_VERSION",
  UNAUTHORIZED: "UNAUTHORIZED",
  REQUEST_EXPIRED: "REQUEST_EXPIRED",
  NONCE_REUSED: "NONCE_REUSED",
  INVALID_SIGNATURE: "INVALID_SIGNATURE",
  UNSUPPORTED_ACTION: "UNSUPPORTED_ACTION",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  SERVICE_NOT_FOUND: "SERVICE_NOT_FOUND",
  STAFF_NOT_FOUND: "STAFF_NOT_FOUND",
  STAFF_NOT_ELIGIBLE: "STAFF_NOT_ELIGIBLE",
  DATE_IN_PAST: "DATE_IN_PAST",
  BELOW_MINIMUM_NOTICE: "BELOW_MINIMUM_NOTICE",
  BEYOND_MAXIMUM_ADVANCE: "BEYOND_MAXIMUM_ADVANCE",
  STAFF_CLOSED_THAT_DAY: "STAFF_CLOSED_THAT_DAY",
  ENDS_AFTER_CLOSING: "ENDS_AFTER_CLOSING",
  STARTS_BEFORE_OPENING: "STARTS_BEFORE_OPENING",
  OVERLAPS_BREAK: "OVERLAPS_BREAK",
  OVERLAPS_TIME_OFF: "OVERLAPS_TIME_OFF",
  OVERLAPS_BLOCK: "OVERLAPS_BLOCK",
  SLOT_UNAVAILABLE: "SLOT_UNAVAILABLE",
  APPOINTMENT_NOT_FOUND: "APPOINTMENT_NOT_FOUND",
  APPOINTMENT_NOT_CHANGEABLE: "APPOINTMENT_NOT_CHANGEABLE",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
};

function ApiError(code, message, retryable) {
  this.name = "ApiError";
  this.code = code;
  this.message = message;
  this.retryable = !!retryable;
}
ApiError.prototype = Object.create(Error.prototype);
ApiError.prototype.constructor = ApiError;
