/**
 * One-time (repeatable, idempotent) CRM initialization from a client's
 * YAML config — the payload this handler consumes is generated by
 * factory/prepare-crm.mjs (see its --output/seed.json). Never overwrites a
 * row an operator has since edited by hand; only fills in what's missing,
 * mirroring setupCRM()'s idempotency contract. See §4 of the factory
 * continuation brief and references/crm-data-model.md.
 */

function importSettingsRows_(rows) {
  var result = { inserted: 0, updated: 0 };
  if (!rows) return result;
  var existing = sheetToObjects_(SHEET_NAMES.SETTINGS);
  for (var i = 0; i < rows.length; i++) {
    var row = rows[i];
    var key = requireString_(row, "key");
    var value = row.value === undefined || row.value === null ? "" : String(row.value);
    var type = optionalString_(row, "type") || "string";
    var found = findRowById_(SHEET_NAMES.SETTINGS, "key", key, existing);
    if (found) {
      updateRowById_(SHEET_NAMES.SETTINGS, "key", key, { value: value, updatedAt: new Date().toISOString() });
      result.updated++;
    } else {
      insertRow_(SHEET_NAMES.SETTINGS, { key: key, value: value, type: type, description: "", updatedAt: new Date().toISOString() });
      result.inserted++;
    }
  }
  return result;
}

function importServiceRows_(rows) {
  var result = { inserted: 0, skipped: 0 };
  if (!rows) return result;
  var existing = sheetToObjects_(SHEET_NAMES.SERVICES);
  for (var i = 0; i < rows.length; i++) {
    var row = rows[i];
    var serviceId = requireString_(row, "serviceId");
    if (findRowById_(SHEET_NAMES.SERVICES, "serviceId", serviceId, existing)) {
      result.skipped++;
      continue;
    }
    var now = new Date().toISOString();
    insertRow_(SHEET_NAMES.SERVICES, {
      serviceId: serviceId,
      name: requireString_(row, "name"),
      description: optionalString_(row, "description") || "",
      price: row.price,
      currency: requireString_(row, "currency"),
      durationMinutes: row.durationMinutes,
      bufferMinutes: row.bufferMinutes || 0,
      active: requireBoolean_(row, "active", true),
      displayOrder: i,
      image: optionalString_(row, "image") || "",
      createdAt: now,
      updatedAt: now,
    });
    result.inserted++;
  }
  return result;
}

function importStaffRows_(rows) {
  var result = { inserted: 0, skipped: 0 };
  if (!rows) return result;
  var existing = sheetToObjects_(SHEET_NAMES.STAFF);
  for (var i = 0; i < rows.length; i++) {
    var row = rows[i];
    var staffId = requireString_(row, "staffId");
    if (findRowById_(SHEET_NAMES.STAFF, "staffId", staffId, existing)) {
      result.skipped++;
      continue;
    }
    var now = new Date().toISOString();
    insertRow_(SHEET_NAMES.STAFF, {
      staffId: staffId,
      name: requireString_(row, "name"),
      biography: optionalString_(row, "biography") || "",
      photoUrl: optionalString_(row, "photoUrl") || "",
      active: requireBoolean_(row, "active", true),
      publicBooking: requireBoolean_(row, "publicBooking", true),
      displayOrder: i,
      createdAt: now,
      updatedAt: now,
    });
    result.inserted++;
  }
  return result;
}

function importStaffServiceRows_(rows) {
  var result = { inserted: 0, skipped: 0 };
  if (!rows) return result;
  var existing = sheetToObjects_(SHEET_NAMES.STAFF_SERVICES);
  for (var i = 0; i < rows.length; i++) {
    var row = rows[i];
    var staffId = requireString_(row, "staffId");
    var serviceId = requireString_(row, "serviceId");
    var already = findRowsWhere_(
      SHEET_NAMES.STAFF_SERVICES,
      function (r) {
        return r.staffId === staffId && r.serviceId === serviceId;
      },
      existing,
    );
    if (already.length > 0) {
      result.skipped++;
      continue;
    }
    insertRow_(SHEET_NAMES.STAFF_SERVICES, {
      staffServiceId: generateUuid_(),
      staffId: staffId,
      serviceId: serviceId,
      active: requireBoolean_(row, "active", true),
      createdAt: new Date().toISOString(),
    });
    result.inserted++;
  }
  return result;
}

function importWorkingHoursRows_(rows) {
  var result = { inserted: 0, skipped: 0 };
  if (!rows) return result;
  var existing = sheetToObjects_(SHEET_NAMES.WORKING_HOURS);
  for (var i = 0; i < rows.length; i++) {
    var row = rows[i];
    var staffId = requireString_(row, "staffId");
    var dayOfWeek = requireString_(row, "dayOfWeek");
    var already = findRowsWhere_(
      SHEET_NAMES.WORKING_HOURS,
      function (r) {
        return r.staffId === staffId && r.dayOfWeek === dayOfWeek;
      },
      existing,
    );
    if (already.length > 0) {
      result.skipped++;
      continue;
    }
    var now = new Date().toISOString();
    insertRow_(SHEET_NAMES.WORKING_HOURS, {
      workingHoursId: generateUuid_(),
      staffId: staffId,
      dayOfWeek: dayOfWeek,
      openingTime: requireLocalTime_(row, "openingTime"),
      closingTime: requireLocalTime_(row, "closingTime"),
      active: true,
      createdAt: now,
      updatedAt: now,
    });
    result.inserted++;
  }
  return result;
}

function importBreakRows_(rows) {
  var result = { inserted: 0, skipped: 0 };
  if (!rows) return result;
  var existing = sheetToObjects_(SHEET_NAMES.BREAKS);
  for (var i = 0; i < rows.length; i++) {
    var row = rows[i];
    var staffId = requireString_(row, "staffId");
    var dayOfWeek = requireString_(row, "dayOfWeek");
    var startTime = requireLocalTime_(row, "startTime");
    var endTime = requireLocalTime_(row, "endTime");
    var already = findRowsWhere_(
      SHEET_NAMES.BREAKS,
      function (r) {
        return r.staffId === staffId && r.dayOfWeek === dayOfWeek && r.startTime === startTime && r.endTime === endTime;
      },
      existing,
    );
    if (already.length > 0) {
      result.skipped++;
      continue;
    }
    insertRow_(SHEET_NAMES.BREAKS, {
      breakId: generateUuid_(),
      staffId: staffId,
      dayOfWeek: dayOfWeek,
      startTime: startTime,
      endTime: endTime,
      active: true,
      createdAt: new Date().toISOString(),
    });
    result.inserted++;
  }
  return result;
}

function actionImportSeed_(payload) {
  var summary = {
    settings: importSettingsRows_(payload.settings),
    services: importServiceRows_(payload.services),
    staff: importStaffRows_(payload.staff),
    staffServices: importStaffServiceRows_(payload.staffServices),
    workingHours: importWorkingHoursRows_(payload.workingHours),
    breaks: importBreakRows_(payload.breaks),
  };
  writeAuditEntry_("importSeed", "Crm", "bulk", "admin", summary);
  return summary;
}
