import type { NextConfig } from "next";
import path from "node:path";

// Pins the workspace root explicitly — this template lives nested inside
// templates/barbershop-booking/ under the main repo, which also has its
// own package-lock.json; without this, Turbopack's root auto-detection
// walks up to the repo root and resolves modules against the wrong
// project entirely. A project generated by factory/create-client.mjs is
// copied to its own independent directory and won't have this problem,
// but the bare template (and its own CI) needs this pin to build
// correctly in place.
const nextConfig: NextConfig = {
  turbopack: {
    root: path.resolve(__dirname),
  },
};

export default nextConfig;
